#!/usr/bin/env bash
# update-dashboard.sh — Generate human-readable dashboard from state files
# Called by monitor.sh every collection cycle. Can also be run manually:
#   OUTPUT_DIR=./output bash scripts/update-dashboard.sh

set -euo pipefail

OUTPUT_DIR="${OUTPUT_DIR:-./output}"
STATE_FILE="$OUTPUT_DIR/state.json"
MONITOR_FILE="$OUTPUT_DIR/monitoring/monitor-status.json"
METRICS_FILE="$OUTPUT_DIR/monitoring/step5-metrics.jsonl"
DASHBOARD="$OUTPUT_DIR/dashboard.md"

TIMESTAMP=$(date -u +%FT%TZ)

# Read state (snapshot copy to avoid reading partial writes)
if [[ -f "$STATE_FILE" ]]; then
    TMPF="/tmp/.dashboard-state-$$.json"
    STATE=$(cp "$STATE_FILE" "$TMPF" 2>/dev/null && cat "$TMPF" && rm -f "$TMPF" || echo '{}')
else
    STATE='{}'
fi

CURRENT_STEP=$(echo "$STATE" | jq -r '.workflow.current_step // 0')
TOTAL_STEPS=6
PCT=$((CURRENT_STEP * 100 / TOTAL_STEPS))

# Progress bar (20 chars)
FILLED=$((PCT / 5))
BAR=""
BAR_EMPTY=""
for ((i=1; i<=20; i++)); do
    if ((i <= FILLED)); then BAR+="█"; else BAR_EMPTY+="░"; fi
done

cat > "$DASHBOARD" << EOF
# 🔬 Chaos Experiment Dashboard
> Last updated: $TIMESTAMP | Auto-refresh: open in IDE Markdown Preview

## Overall Progress
\`${BAR}${BAR_EMPTY}\` ${PCT}% — Step ${CURRENT_STEP}/${TOTAL_STEPS}

## Experiment Status
| # | Experiment | Status | Duration | Result |
|---|-----------|--------|----------|--------|
EOF

# Parse experiments array
echo "$STATE" | jq -r '.experiments[]? |
    "| \(.id) | \(.name) | \(.status) | \(.elapsed_seconds // "—")s | \(.result // "—") |"' \
    >> "$DASHBOARD" 2>/dev/null

# Current running experiment details
RUNNING_EXP=$(echo "$STATE" | jq -r '.experiments[]? | select(.status == "running")' 2>/dev/null || echo "")
if [[ -n "$RUNNING_EXP" ]]; then
    RUN_ID=$(echo "$RUNNING_EXP" | jq -r '.fis_id // .cm_name // "—"')
    RUN_NAME=$(echo "$RUNNING_EXP" | jq -r '.name // "—"')
    cat >> "$DASHBOARD" << EOF

## Current: $(echo "$RUNNING_EXP" | jq -r '.id') — $RUN_NAME
- Backend ID: $RUN_ID
- Started: $(echo "$RUNNING_EXP" | jq -r '.started_at // "—"')
EOF
fi

# Monitor heartbeat
if [[ -f "$MONITOR_FILE" ]]; then
    LAST_COLLECT=$(jq -r '.last_collect // "—"' "$MONITOR_FILE")
    SAMPLES=$(jq -r '.samples // 0' "$MONITOR_FILE")
    cat >> "$DASHBOARD" << EOF

## Monitor Status
- Last collection: $LAST_COLLECT
- Total samples: $SAMPLES
- Status: ✅ Active
EOF
fi

# Latest metrics (last line of JSONL)
if [[ -f "$METRICS_FILE" ]]; then
    LAST_METRICS=$(tail -1 "$METRICS_FILE" 2>/dev/null || echo '{}')
    METRIC_COUNT=$(echo "$LAST_METRICS" | jq '.metrics | length' 2>/dev/null || echo 0)
    cat >> "$DASHBOARD" << EOF

## Latest Metrics (${METRIC_COUNT} data points)
\`\`\`json
$(echo "$LAST_METRICS" | jq -c '.metrics[]? | {id: .Id, values: .Values[0:3]}' 2>/dev/null || echo "No data yet")
\`\`\`
EOF
fi

# Timeline from state
cat >> "$DASHBOARD" << EOF

## Timeline
EOF
echo "$STATE" | jq -r '.experiments[]? |
    if .completed_at then "- \(.completed_at) \(.id) → \(.result // .status)"
    elif .started_at then "- \(.started_at) \(.id) started"
    else empty end' >> "$DASHBOARD" 2>/dev/null

echo "" >> "$DASHBOARD"
echo "_Dashboard generated by update-dashboard.sh — do not edit manually_" >> "$DASHBOARD"
